name: Create Release

on:
  push:
    tags:
      - v1.*
  
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          output=$(python3 test/get_changes.py "${{ github.ref }}")
          echo "::set-output name=changelog::$output"
        id: set_changelog
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "plugin_manager.py"
          body: |
            ## Changelog
            ${{ steps.set_changelog.outputs.changelog }}
          tag: ${{ github.ref }}
          name: ${{ github.ref_name}}